
--PARA B1 LOTAIP
SELECT all YP_NOM_EMPLOYEES.nombre as "NOMBRE", YP_NOM_CHARGES.descripcion as "PUESTO INSTITUCIONAL", 
YP_NOM_PROJECT.descripcion as "UNIDAD A LA QUE PERTENECE", YP_NOM_EMPLOYEES.DireccionT as "DIRECCION INSTITUCIONAL", 
YP_NOM_EMPLOYEES.CiudadT as "CIUDAD", YP_NOM_EMPLOYEES.TelefonoT AS "TELEFONO", '200' AS "EXTENSION", YP_NOM_EMPLOYEES.MAIL AS "MAIL"
FROM YP_NOM_EMPLOYEES 
inner join YP_NOM_PROJECT ON YP_NOM_EMPLOYEES.proyecto=YP_NOM_PROJECT.codigo   
inner join YP_NOM_CHARGES ON YP_NOM_EMPLOYEES.cargo=YP_NOM_CHARGES.codigo
where (CAST(fechai AS DATE)<= '2022-06-30' and YP_NOM_EMPLOYEES.PagoAutomatico=1 ) 
OR (CAST(fechas AS DATE)>= '2022-06-01' and CAST(fechas AS DATE)<= '2022-06-30' )
ORDER BY YP_NOM_EMPLOYEES.NOMBRE

--PARA B2 LOTAIP
SELECT all YP_NOM_PROJECT.descripcion as "UNIDAD A LA QUE PERTENECE", YP_NOM_EMPLOYEES.nombre as "NOMBRE", 
YP_NOM_CHARGES.nombre as "PUESTO INSTITUCIONAL"
FROM YP_NOM_EMPLOYEES 
inner join YP_NOM_PROJECT ON YP_NOM_EMPLOYEES.proyecto=YP_NOM_PROJECT.codigo   
inner join YP_NOM_CHARGES ON YP_NOM_EMPLOYEES.cargo=YP_NOM_CHARGES.codigo
where ((CAST(fechai AS DATE)<= '2022-06-30' and YP_NOM_EMPLOYEES.PagoAutomatico=1 ) 
OR (CAST(fechas AS DATE)>= '2022-06-01' and CAST(fechas AS DATE)<= '2022-06-30' )) AND YP_NOM_EMPLOYEES.nivel=1 
AND YP_NOM_CHARGES.nombre NOT LIKE 'ASESOR%'  
/*AND YP_NOM_EMPLOYEES.fechas='1900-01-01'*/
ORDER BY YP_NOM_EMPLOYEES.nombre

--PARA VER ASESOR B2
SELECT all YP_NOM_PROJECT.descripcion as "UNIDAD A LA QUE PERTENECE", YP_NOM_EMPLOYEES.nombre as "NOMBRE", 
YP_NOM_CHARGES.nombre as "PUESTO INSTITUCIONAL"
FROM YP_NOM_EMPLOYEES 
inner join YP_NOM_PROJECT ON YP_NOM_EMPLOYEES.proyecto=YP_NOM_PROJECT.codigo   
inner join YP_NOM_CHARGES ON YP_NOM_EMPLOYEES.cargo=YP_NOM_CHARGES.codigo
where fechai<= '28/02/2022' and YP_NOM_EMPLOYEES.PagoAutomatico=1 AND YP_NOM_CHARGES.nombre LIKE 'ASESOR%' 
--AND YP_NOM_EMPLOYEES.nombre ='PAZMIÑO REAL DANIEL ADRIAN' 

--PARA VER FUNCIONARIOS QUE NO ESTAN EN NIVEL 1 Y 2
select * 
from YP_NOM_EMPLOYEES
where nivel not in (2,1) and YP_NOM_EMPLOYEES.PagoAutomatico=1

--PARA VER FUNCIONARIOS QUE INGRESARON EN MES ESPECIFICO
select CODIGO, NOMBRE, fechai  
from YP_NOM_EMPLOYEES
where year(fechai)='2022' and month(fechai)= '01' 
order by nombre